INSERT INTO USER (EMAIL_ADDRESS, PASSWORD, NAME) VALUES ('victor@gmail.com', 'ffc150a160d37e92012c196b6af4160d', 'Victor');
INSERT INTO USER (EMAIL_ADDRESS, PASSWORD, NAME) VALUES ('nacho@gmail.com', 'b623e24add2f342de2acdf8b4edad496', 'Nacho');

INSERT INTO TAG (NAME) VALUES ('Technology');
INSERT INTO TAG (NAME) VALUES ('Cars');

INSERT INTO BLOGPOST (CREATOR_ID, TITLE, BODY) VALUES (1, 'Test title', 'Test body');

--INSERT INTO BLOGPOST_TAG (TAG_ID, BLOGPOST_ID) (1,1);
