INSERT INTO USER (EMAIL_ADDRESS, PASSWORD, NAME) VALUES ('victor@gmail.com', '1234', 'Victor');
INSERT INTO USER (EMAIL_ADDRESS, PASSWORD, NAME) VALUES ('nacho@gmail.com', '1234', 'Nacho');

INSERT INTO TAG (NAME) VALUES ('Technology');
INSERT INTO TAG (NAME) VALUES ('Cars');

INSERT INTO BLOGPOST (CREATOR_ID, TITLE, BODY) VALUES (1, 'Test title', 'Test body');

INSERT INTO BLOGPOST_TAGS (BLOG_POST_ID, TAGS_ID) VALUES (1, 1);
